In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
#2
import pandas
data = pandas.read_csv('height_weight.csv')
data.head(3)

height    weight
0  65.78331  112.9925
1  71.51521  136.4873
2  69.39874  153.0269

In [3]:
#standardize data
temp = data.iloc[:,:].values
data_s = (temp -temp.mean()) / temp.std()
data_s

array([[-1.03424254,  0.50343321],
       [-0.84754576,  1.2686949 ],
       [-0.91648244,  1.80741505],
       ..., 
       [-1.06957484,  0.67518291],
       [-0.97737688,  1.13127234],
       [-0.93345644,  0.89043841]])

In [4]:
# x=data['height'].copy()
# del x[0]
# height=pandas.DataFrame.as_matrix(x)
# x=height.astype(np.float)
# x
x=data_s[:,0]
x

array([-1.03424254, -0.84754576, -0.91648244, ..., -1.06957484,
       -0.97737688, -0.93345644])

In [5]:
# y = data['weight'].copy()
# del y[0]
# height=pandas.DataFrame.as_matrix(y)
# y=height.astype(np.float)
y=data_s[:,1]
y

array([ 0.50343321,  1.2686949 ,  1.80741505, ...,  0.67518291,
        1.13127234,  0.89043841])

In [6]:
x,y

(array([-1.03424254, -0.84754576, -0.91648244, ..., -1.06957484,
        -0.97737688, -0.93345644]),
 array([ 0.50343321,  1.2686949 ,  1.80741505, ...,  0.67518291,
         1.13127234,  0.89043841]))

In [7]:
sx = x.std()
sy = y.std()
r = np.corrcoef(x,y)[0,1]
print(r)
x_ave = x.mean()
y_ave = y.mean()

0.502858520603


In [8]:
wopt = r*sy/sx
bopt = y_ave - x_ave*r*sy/sx
print(wopt,bopt)


3.0834764454 3.92938992431


In [9]:
def MSE(w,b,x,y):
    err = y-(w*x+b)
    return (err*err).mean()
MSE(3.0834764454  ,3.92938992431,x,y)

0.10777576674981452

In [10]:
def dMSE_w(w,b,x,y):
    return (-2*x*(y-w*x-b)).mean()

In [11]:
def dMSE_b(w,b,x,y):
    return (-2*(y-w*x-b)).mean()

In [18]:
kmax=100000
MOD = 10000
b=4
w=4

learning_rate=0.00001

fmin=MSE(w,b,x,y)
k=0

while (MSE(w,b,x,y) <= fmin) and (k < kmax):
    fmin=MSE(w,b,x,y)
    b = b - dMSE_b(w,b,x,y)*learning_rate
    w = w - dMSE_w(w,b,x,y)*learning_rate
    k = k + 1
    if(k % MOD == 0):
        print(k,w,b,fmin)
print(k,w,b,fmin)

10000 3.86981788985 4.13461414145 0.414263465638
20000 3.78122046512 4.22609820379 0.250059747791
30000 3.72090343391 4.28825095227 0.174116585099
40000 3.67981898776 4.33045647023 0.138993132457
50000 3.65181401172 4.35909656205 0.122748427319
60000 3.63270397604 4.37851128156 0.115234972634
70000 3.61964312055 4.39165215568 0.111759642671
80000 3.61069613799 4.40052642011 0.110151909181
90000 3.60454688997 4.4064991294 0.109407922474
100000 3.60030031431 4.41049861193 0.109063411149
100000 3.60030031431 4.41049861193 0.109063411149


In [20]:
(0.109063411149*temp.std())+temp.mean()

100.8846945670209